services:
    konecty-mongodb:
        image: mongo:6
        container_name: konecty-mongodb
        restart: always
        env_file:
            - .env
        ports:
            - '${MONGO_PORT:-27017}:27017'
        command: ['mongod', '--bind_ip_all', '--replSet', 'rs0']

    konecty-mongodb-init:
        image: mongo:6
        container_name: konecty-mongodb-init
        depends_on:
            - konecty-mongodb
        command:
            - /bin/bash
            - -c
            - |
                echo 'Waiting 10 seconds before checking replica set status';
                sleep 10;
                echo 'Checking replica set status';
                if ! mongosh --host konecty-mongodb --eval 'rs.status()' | grep "set: 'rs0'"; then
                    echo 'Initiating replica set';
                    mongosh --host konecty-mongodb --eval 'rs.initiate({_id : "rs0", members: [ { _id: 0, host: "konecty-mongodb:27017" } ] })';
                else
                    echo 'Replica set already initialized';
                fi

    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

    konecty:
        container_name: konecty
        image: konecty/konecty:2.2.1
        ports:
            - '${PORT:-3000}:${PORT:-3000}'
        env_file:
            - .env
        environment:
            - MONGO_URL=mongodb://konecty-mongodb:27017/${KONMETA_NAMESPACE}?directConnection=true
        depends_on:
            konecty-mongodb-init:
                condition: service_completed_successfully
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${PORT:-3000}/liveness']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s
