apiVersion: apps/v1
kind: Deployment
metadata:
  name: konecty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konecty
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: konecty
    spec:
      containers:
        - name: konecty
          image: konecty/konecty:3.2.1
          env:
            - name: MONGO_URL
              value: "mongodb://localhost:27017/konecty"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: LOG_PRETTY
              value: "true"
            - name: LOG_LEVEL
              value: "info"
            - name: DISABLE_REINDEX
              value: 'true'
            - name: DISABLE_TELEMETRY_LOGS
              value: 'true'
            - name: DISABLE_SENDMAIL
              value: 'true'
            - name: TZ
              value: America/Sao_Paulo
            - name: UI_URL
              value: ui-v2.konecty.com
            - name: BLOB_URL
              value: https://konecty.com
            - name: PREVIEW_URL
              value: https://konecty.com
            - name: KONECTY_RIA
              value: legacy
            - name: HOST
              value: '::'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 300m
              memory: 500Mi
